[2024-08-03T15:46:20.716+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: excel_to_oracle_dag.load_excel_to_oracle scheduled__2024-08-02T10:00:00+00:00 [queued]>
[2024-08-03T15:46:20.727+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: excel_to_oracle_dag.load_excel_to_oracle scheduled__2024-08-02T10:00:00+00:00 [queued]>
[2024-08-03T15:46:20.727+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-08-03T15:46:20.728+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2024-08-03T15:46:20.728+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-08-03T15:46:20.742+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): load_excel_to_oracle> on 2024-08-02 10:00:00+00:00
[2024-08-03T15:46:20.749+0000] {standard_task_runner.py:55} INFO - Started process 6704 to run task
[2024-08-03T15:46:20.752+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'excel_to_oracle_dag', 'load_excel_to_oracle', 'scheduled__2024-08-02T10:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/excel_to_oracle_dag.py', '--cfg-path', '/tmp/tmptb12055u']
[2024-08-03T15:46:20.753+0000] {standard_task_runner.py:83} INFO - Job 13: Subtask load_excel_to_oracle
[2024-08-03T15:46:20.814+0000] {task_command.py:376} INFO - Running <TaskInstance: excel_to_oracle_dag.load_excel_to_oracle scheduled__2024-08-02T10:00:00+00:00 [running]> on host b6edf892b8ff
[2024-08-03T15:46:20.885+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=excel_to_oracle_dag
AIRFLOW_CTX_TASK_ID=load_excel_to_oracle
AIRFLOW_CTX_EXECUTION_DATE=2024-08-02T10:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-08-02T10:00:00+00:00
[2024-08-03T15:46:20.897+0000] {base.py:71} INFO - Using connection ID 'Connection bai test' for task execution.
[2024-08-03T15:46:20.900+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/excel_to_oracle_dag.py", line 33, in load_excel_to_oracle
    connection = cx_Oracle.connect(user=conn.login, password=conn.password, dsn=dsn)
cx_Oracle.DatabaseError: DPI-1047: Cannot locate a 64-bit Oracle Client library: "libclntsh.so: cannot open shared object file: No such file or directory". See https://cx-oracle.readthedocs.io/en/latest/user_guide/installation.html for help
[2024-08-03T15:46:20.911+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=excel_to_oracle_dag, task_id=load_excel_to_oracle, execution_date=20240802T100000, start_date=20240803T154620, end_date=20240803T154620
[2024-08-03T15:46:20.924+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 13 for task load_excel_to_oracle (DPI-1047: Cannot locate a 64-bit Oracle Client library: "libclntsh.so: cannot open shared object file: No such file or directory". See https://cx-oracle.readthedocs.io/en/latest/user_guide/installation.html for help; 6704)
[2024-08-03T15:46:20.965+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2024-08-03T15:46:20.984+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
